### ISSUE TITLE
Compiling libraries using gfortran

### ISSUE THREAD

**Issue by covarj** [yanhuay/seisDD#1]
When compiling libraries (make -f make_lib) using gfortran I get the following message:

Error: Dummy argument 'adj1' of procedure 'mt_misfit_dd' at (1) has an attribute that requires an explicit interface for this procedure
make: *** [src/adjoint_lib.o] Error 1

Do you know any work around for this?

Thanks,

RC

**Comment by fjsimons** [comment]
Please compile the codes using the `ifort` compiler.
